POST http://localhost:3000/videos
Content-Type: application/json

{
  "title": "Ameriacan Pie",
  "duration": 200
}

###

GET http://localhost:3000

###

PUT http://localhost:3000/videos/26a62751-0bcc-47b4-baaf-1e59b1118efa
Content-Type: application/json

{
  "title": "American Pie - O retorno",
  "duration": 150
}

###

DELETE http://localhost:3000/videos/5d0415ae-d45f-4859-b26b-a55725fcd497